name: BUILD_PUBLISH

on:
  release:
    types: [created]

jobs:
  build-glibc:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run prebuild
        env:
          prebuild_upload: ${{ secrets.GITHUB_TOKEN }}

  build-musl:
    runs-on: ubuntu-latest
    container:
      image: node:14-alpine
    steps:
      - uses: actions/checkout@v2
      - name: install sdk and python
        run: apk add --no-cache alpine-sdk python
      - run: npm i
      - run: npm run prebuild
        env:
          prebuild_upload: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: [build-glibc, build-musl]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
