name: BUILD_PUBLISH

on:
  release:
    types: [created]

jobs:
  build-linux_macos_windows-glibc:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-22.04, macos-12, windows-2022]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run prebuild_electron
        env:
          prebuild_upload: ${{ secrets.AT }}
      - run: npm run prebuild_node
        env:
          prebuild_upload: ${{ secrets.AT }}

  build-linux-musl:
    runs-on: ubuntu-22.04
    container:
      image: node:18-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install sdk and python
        run: apk add --no-cache alpine-sdk python3
      - run: npm i
      - run: npm run prebuild_electron
        env:
          prebuild_upload: ${{ secrets.AT }}
      - run: npm run prebuild_node
        env:
          prebuild_upload: ${{ secrets.AT }}

  publish:
    needs: [build-linux_macos_windows-glibc, build-linux-musl]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
